apiVersion: v1
kind: Service
metadata: 
  name: nexus-search-backend
  labels:
    app: nexus-search-backend
spec:
  type: LoadBalancer
  selector:
    app: nexus-search-backend
  ports:
    - name: nexus-search-backend-port
      protocol: TCP
      port: 3000
      targetPort: 3000